export const MODAL_IDS = {
  WEATHER_MAP: 'WEATHER_MAP_MODAL',
  LENS_EDIT: 'LENS_EDIT_MODAL',
  ADD_LENS: 'ADD_LENS_MODAL',
  ADD_LENS_PACK: 'ADD_LENS_PACK_MODAL',
  LENS_TAKE_OFF_CONFIRM: 'LENS_TAKE_OFF_CONFIRM_MODAL',
  LENS_DISCARD_CONFIRM: 'LENS_DISCARD_CONFIRM_MODAL'
  // Add new IDs here
} as const

export type ModalId = (typeof MODAL_IDS)[keyof typeof MODAL_IDS]
